import mongoose from 'mongoose';

export const GUESSES = ['girl', 'boy'];

const voteSchema = new mongoose.Schema(
  {
    // Anonymous id generated by the browser, used to allow one vote per participant
    voterId: { type: String, required: true, unique: true },
    relation: { type: String, required: true, trim: true, maxlength: 40 },
    // Optional image, resized on the client and stored as a data URL
    photo: { type: String },
    guess: { type: String, enum: GUESSES, required: true },
  },
  { timestamps: true }
);

export const Vote = mongoose.model('Vote', voteSchema);
